### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by arademaker** [own-pt/delphin-rdf#27]
```
% python test.py
Connecting to AllegroGraph server -- host:'127.0.0.1' port:10035
Available catalogs:
  - <root catalog>
  - system
Available repositories in catalog 'None':
  - own
  - te
Repository te is up!
It contains 0 statement(s).
graph 1
NOTE: parsed 1 / 1 sentences, avg 238028k, time 10.03111s
Traceback (most recent call last):
  File "/Users/ar/venv/lib/python3.9/site-packages/rdflib/plugin.py", line 103, in get
    p = _plugins[(name, kind)]
KeyError: ('a', <class 'rdflib.store.Store'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ar/hpsg/sick/test.py", line 96, in <module>
    g1 = simplify(filter1(process(sent1,"a")))
  File "/Users/ar/hpsg/sick/test.py", line 75, in process
    triples = rdf.dmrs_to_rdf(d, "http://example.com",id)
  File "/Users/ar/venv/lib/python3.9/site-packages/delphin/rdf/_dmrs_parser.py", line 39, in dmrs_to_rdf
    defaultGraph = Graph(store, identifier=BNode())
  File "/Users/ar/venv/lib/python3.9/site-packages/rdflib/graph.py", line 306, in __init__
    self.__store = store = plugin.get(store, Store)()
  File "/Users/ar/venv/lib/python3.9/site-packages/rdflib/plugin.py", line 105, in get
    raise PluginException(
rdflib.plugin.PluginException: No plugin registered for (a, <class 'rdflib.store.Store'>)
```

**Comment by arademaker** [comment]
@yfaria please can you report here your solution and submit the PR to solve this issue ASAP.

**Comment by arademaker** [comment]
Can we close this issue? I was able to execute the conversion of a profile, but I am not sure if @yfaria still has something to do here. @yfaria ? Please comment and close.

**Comment by yfaria** [comment]
Closing as #28 solves it.
